# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
        ),
    ]
