# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0003_auto_20170128_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meliprofile',
            name='meli_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
